# Generated by Django 4.2.23 on 2025-08-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=10)),
                ('FirstName', models.CharField(max_length=300)),
                ('LastName', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=400)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('Address', models.TextField()),
                ('Isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
